import type { AppConfig } from './types';

export const defaultConfig: AppConfig = {
  version: 1,
  app: {
    name: 'Singing Boat',
    randomSeed: 'singing-boat-v1',
  },
  signalk: {
    enabled: true,
    protocol: 'ws',
    host: 'localhost',
    port: 3000,
    version: 'v1',
    subscribe: 'self',
    token: null,
    reconnect: {
      minDelayMs: 500,
      maxDelayMs: 10000,
      jitter: true,
    },
    stalePolicy: {
      defaultStaleAfterMs: 5000,
      onDisconnect: 'fade_then_silence',
      fadeMs: 3000,
    },
  },
  midi: {
    output: {
      mode: 'selected_or_virtual',
      preferredName: 'Singing Boat',
      createVirtual: true,
    },
    panicOnStop: true,
    sendClock: false,
    channels: {
      melody: 1,
      drone: 2,
      bass: 3,
      warnings: 4,
      control: 16,
    },
  },
  clock: {
    bpm: {
      base: 84,
      min: 60,
      max: 128,
      source: 'boatSpeed',
      amount: 0.35,
    },
    beatsPerBar: 4,
    phraseLengthBars: 8,
    swing: 0,
  },
  sensors: {
    windSpeed: {
      path: 'environment.wind.speedApparent',
      sourceUnits: 'm/s',
      displayUnits: 'kn',
      normalize: { min: 0, max: 20, curve: 'easeInOut' },
      smoothing: { type: 'ema', alpha: 0.12 },
      staleAfterMs: 5000,
    },
    windAngle: {
      path: 'environment.wind.angleApparent',
      sourceUnits: 'rad',
      displayUnits: 'deg',
      normalize: { min: -3.14159, max: 3.14159, mode: 'bipolarCircular' },
      smoothing: { type: 'emaCircular', alpha: 0.2 },
      staleAfterMs: 5000,
    },
    boatSpeed: {
      path: 'navigation.speedThroughWater',
      sourceUnits: 'm/s',
      displayUnits: 'kn',
      normalize: { min: 0, max: 5, curve: 'linear' },
      smoothing: { type: 'ema', alpha: 0.15 },
      staleAfterMs: 5000,
    },
    depth: {
      path: 'navigation.depth.belowTransducer',
      sourceUnits: 'm',
      displayUnits: 'm',
      normalize: { min: 1, max: 30, invert: true, curve: 'easeInOut' },
      smoothing: { type: 'ema', alpha: 0.2 },
      staleAfterMs: 5000,
    },
    heel: {
      path: 'navigation.attitude.roll',
      sourceUnits: 'rad',
      displayUnits: 'deg',
      normalize: { min: -0.7, max: 0.7, mode: 'bipolar' },
      smoothing: { type: 'ema', alpha: 0.2 },
      deadband: 0.02,
      staleAfterMs: 5000,
    },
    windGust: {
      derivedFrom: 'windSpeed',
      mode: 'deltaAboveAverage',
      windowMs: 10000,
      normalize: { min: 0, max: 0.4 },
    },
  },
  harmony: {
    key: 'D',
    mode: 'dorian',
    progression: {
      type: 'roman',
      chords: ['i7', 'IV7', 'VIImaj7', 'v7'],
      advance: {
        mode: 'sensor_or_time',
        sensor: 'windSpeed',
        thresholds: [0.2, 0.45, 0.7],
        barsPerChord: 4,
      },
    },
    quantize: {
      enabled: true,
      allowPassingTones: true,
      passingToneProbability: 0.15,
    },
    voiceLeading: {
      mode: 'commonTone',
      maxLeapSemitones: 7,
    },
    tension: {
      sources: [
        { sensor: 'heel', weight: 0.5 },
        { sensor: 'windGust', weight: 0.3 },
        { sensor: 'depth', weight: 0.2 },
      ],
    },
  },
  motifs: {
    windMelody: {
      type: 'rising',
      channel: 'melody',
      range: { low: 'D3', high: 'A5' },
      rhythm: { grid: '1/8', densitySensor: 'windSpeed', densityMin: 0.1, densityMax: 0.85 },
      pitch: { source: 'windAngle', mode: 'scaleDegree', contour: 'sensor_delta' },
      velocity: { source: 'windSpeed', min: 35, max: 110 },
    },
    drone: {
      type: 'drone',
      channel: 'drone',
      notes: 'chord_root_and_fifth',
      octave: 2,
    },
    bassPulse: {
      type: 'pulse',
      channel: 'bass',
      rhythm: { grid: '1/4', densitySensor: 'boatSpeed', densityMin: 0.15, densityMax: 0.6 },
      pitch: { mode: 'chordRoot', octave: 2 },
      velocity: { source: 'boatSpeed', min: 30, max: 100 },
    },
    gustAccent: {
      type: 'arpeggio',
      channel: 'melody',
      trigger: { sensor: 'windGust', above: 0.65, cooldownMs: 3000 },
      rhythm: { grid: '1/16', steps: 6 },
      pitch: { mode: 'chordTones', contour: 'up_then_down' },
      velocity: { fixed: 105 },
    },
    shallowWarning: {
      type: 'warning',
      channel: 'warnings',
      trigger: { sensor: 'depth', above: 0.8, hysteresis: 0.1 },
      rhythm: { grid: '1/4', repeats: 3 },
      pitch: { degrees: [1, 5, 1], octave: 5 },
      velocity: { fixed: 115 },
    },
  },
  arrangement: {
    level: 2,
    phraseLengthBars: 8,
    transition: {
      defaultDurationMs: 4000,
      quantizeTo: 'bar',
      mode: 'crossfade_layers_common_tone',
    },
    scenes: {
      calm: {
        when: { all: [{ sensor: 'windSpeed', below: 0.2 }, { sensor: 'boatSpeed', below: 0.15 }] },
        layers: { drone: { enabled: true, gain: 0.45 }, bassPulse: { enabled: false }, windMelody: { enabled: true, density: 0.15 } },
      },
      steady_sailing: {
        when: { all: [{ sensor: 'boatSpeed', above: 0.2 }, { sensor: 'windSpeed', between: [0.2, 0.65] }] },
        layers: { drone: { enabled: true, gain: 0.6 }, bassPulse: { enabled: true, density: 0.35 }, windMelody: { enabled: true, density: 0.4 } },
      },
      fast_reach: {
        when: { all: [{ sensor: 'boatSpeed', above: 0.6 }, { sensor: 'windSpeed', above: 0.45 }] },
        layers: { drone: { enabled: true, gain: 0.7 }, bassPulse: { enabled: true, density: 0.6 }, windMelody: { enabled: true, density: 0.7 } },
      },
      gusty: {
        when: { any: [{ sensor: 'windGust', above: 0.65 }, { sensor: 'heel', absAbove: 0.65 }] },
        priority: 70,
        layers: { drone: { enabled: true, gain: 0.75 }, bassPulse: { enabled: true, density: 0.8 }, windMelody: { enabled: true, density: 0.85 }, gustAccent: { enabled: true } },
      },
      shallow_water: {
        when: { any: [{ sensor: 'depth', above: 0.8 }] },
        priority: 90,
        interrupt: true,
        layers: { drone: { enabled: true, gain: 0.55 }, bassPulse: { enabled: false }, windMelody: { enabled: true, density: 0.25 }, shallowWarning: { enabled: true } },
      },
      maneuver: { when: { any: [{ sensor: 'heel', absAbove: 0.7 }] }, layers: { drone: { enabled: true } } },
      harbor: { when: { all: [{ sensor: 'boatSpeed', below: 0.1 }] }, layers: { drone: { enabled: true } } },
      connection_lost: { when: { any: [{ sensor: 'connection', above: 0.5 }] }, layers: { drone: { enabled: false } } },
    },
  },
  mappings: [
    {
      id: 'wind-expression',
      source: 'windSpeed',
      target: { type: 'cc', channel: 'melody', controller: 11 },
      transform: { curve: 'easeInOut', min: 20, max: 110 },
      smoothing: { rampMs: 500 },
    },
    {
      id: 'heel-pitchbend',
      source: 'heel',
      target: { type: 'pitchBend', channel: 'drone' },
      transform: { mode: 'bipolar', min: -0.15, max: 0.15 },
      smoothing: { rampMs: 250 },
    },
  ],
};
